# Generated by Django 3.2.23 on 2024-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewrating',
        ),
    ]
