# Generated by Django 3.2.23 on 2024-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0002_delete_viewrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaints',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manageplaylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='LOGIN',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Complaints',
        ),
        migrations.DeleteModel(
            name='Manageplaylist',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
