# Generated by Django 3.2.23 on 2024-01-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0004_chat_complaints_manageplaylist_user_viewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viewrating',
        ),
    ]
