# Generated by Django 3.2.23 on 2024-01-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
