# Generated by Django 3.2.23 on 2024-01-20 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0007_auto_20240120_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manageplaylist',
            name='user',
        ),
        migrations.AddField(
            model_name='manageplaylist',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emo.login'),
            preserve_default=False,
        ),
    ]
