# Generated by Django 5.0.1 on 2024-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0008_auto_20240120_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(),
        ),
    ]
