# Generated by Django 3.2.25 on 2024-03-29 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0009_alter_chat_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('emotion', models.CharField(max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emo.login')),
            ],
        ),
    ]
