# Generated by Django 3.2.25 on 2024-04-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emo', '0010_manage_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='post',
        ),
    ]
